### ISSUE TITLE
zsh: parse error near `}'

### ISSUE THREAD

**Issue by slussshy** [Pandora-Labs-Org/erc404#13]
I am a new learner here.  I am trying to do a Quickstart in your latest tutorial and everything works fine installing forge etc.   when I get to the step that runs the example code I get an error at the end zsh: parse error near `}':

 //SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {Strings} from "@openzeppelin/contracts/utils/Strings.sol";
import {ERC404} from "erc404/ERC404.sol";

contract ExampleERC404 is Ownable, ERC404 {
  constructor(
    string memory name_,
    string memory symbol_,
    uint8 decimals_,
    uint256 maxTotalSupplyERC721_,
    address initialOwner_
  ) ERC404(name_, symbol_, decimals_) Ownable(initialOwner_) {
    _setERC721TransferExempt(initialOwner_, true);
    _mintERC20(initialOwner_, maxTotalSupplyERC721_ * units, false);
  }

  function tokenURI(uint256 id_) public pure override returns (string memory) {
    return string.concat("https://example.com/token/", Strings.toString(id_));
  }

  function setERC721TransferExempt(address account_, bool value_) external onlyOwner {
    _setERC721TransferExempt(account_, value_);
  }
}

zsh: parse error near `}'

How do I get around this problem? I have tried reinstalling zsh with homebrew.  still the same.  sorry if this is basic stuff but I searched the internet everywhere and can't find a straight answer.

**Comment by mathdroid** [comment]
![image](https://github.com/Pandora-Labs-Org/erc404/assets/3748658/8a6d7700-d560-4f65-bffd-ee1a7f835e1a)

Make a file with this content instead of copy-pasting this to the terminal :) @slussshy

**Comment by slussshy** [comment]
thanks!  will do!
