### ISSUE TITLE
Enable support of ERC-721 and ERC-20 into ERC-165 compliance

### ISSUE THREAD

**Issue by irzhywau** [Pandora-Labs-Org/erc404#35]
As far as know, this contract type is intended to behaves as ERC-721 and ERC-20, maybe it would be better to these both standard in the `supportsInterface` method

https://github.com/Pandora-Labs-Org/erc404/blob/e78af836be094c0c9de5c4a691e8b458b7d9cfad/contracts/ERC404.sol#L426

**Comment by 0xacme** [comment]
It is intended to behave very closely to ERC-721 and ERC-20 standards, though there are still deviations from these interfaces, so we've decided to go with the strict approach of not claiming to conform.

For all standard purposes, ERC404 can be treated as an ERC-721 or ERC-20 and will function as expected, though interfaces are not implemented exactly, hence not supported.
